pagopa/pagopa-debt-position

gpd/api-test/DEBT_POSITION.postman_collection.json
gpd/doc/db/re.puml
gpd/src/main/java/it/gov/pagopa/debtposition/DebtPositionApplication.java
gpd/src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/api/IDebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/api/impl/DebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/mapper/ConvertPPModelToPPEntityForUpdate.java
gpd/src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
gpd/src/main/java/it/gov/pagopa/debtposition/entity/PaymentPosition.java
gpd/src/main/java/it/gov/pagopa/debtposition/entity/Transfer.java
gpd/src/main/java/it/gov/pagopa/debtposition/exception/AppError.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/enumeration/DebtPositionStatus.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
gpd/src/main/java/it/gov/pagopa/debtposition/repository/PaymentOptionRepository.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/PaymentPositionService.java
gpd/src/main/java/it/gov/pagopa/debtposition/util/HttpStatusExplainMessage.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

1. Added PUT Method for Update Payment Position
2. Produced the JUnit test
3. Produced postam integration test
4. Updated er diagram
Assigned task
Manual test with JUnit and postman.
An example of update call:
`
curl --location --request PUT 'http://localhost:8080/organizations/25355091147/debtpositions/efP4X8SupqGr5YmOXOZnknmUCkPc6VFkQNg' \
--header 'Content-Type: application/json' \
--data-raw '{
"iupd": "efP4X8SupqGr5YmOXOZnknmUCkPc6VFkQNg",
"type": "F",
"fiscalCode": "JHNDOE00A01F205N",
"fullName": "John Doe",
"streetName": "streetName",
"civicNumber": "11",
"postalCode": "00100",
"city": "city",
"province": "RM",
"region": "RM",
"country": "IT",
"email": "lorem@lorem.com",
"phone": "333-123456789",
"companyName": "companyName",
"officeName": "officeName",
"validityDate": …

[PPD-9] aggiornare una posizione debitoria

---

gpd/api-test/DEBT_POSITION.postman_collection.json
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/scheduler/Scheduler.java
gpd/src/main/java/it/gov/pagopa/debtposition/exception/AppError.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/TransferModel.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionModelResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/response/TransferModelResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/repository/PaymentOptionRepository.java
gpd/src/main/java/it/gov/pagopa/debtposition/repository/PaymentPositionRepository.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java

- Added service to retrieve a payment option by iuv
- Added junit test
- Added postman integration test
- assigned task
manual test with postman and JUnit test

[PPD-54] verificare iuv

---

gpd/openapi/openapi.json

update api spec

---

gpd/openapi/openapi.json
gpd/pom.xml
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/exception/AppError.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/enumeration/DebtPositionStatus.java
gpd/src/main/java/it/gov/pagopa/debtposition/repository/PaymentPositionRepository.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/main/java/it/gov/pagopa/debtposition/validation/DebtPositionValidation.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

- Added report transfer service
- Added junit test for service
- Added integration postaman test
- Updated openapi file
- Assigned Task
Manual postman test and Junit Test

[PPD-56] rendicontare un versamento

---

gpd/api-test/DEBT_POSITION.postman_collection.json
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/filterandorder/FilterAndOrder.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/filterandorder/Order.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
gpd/src/main/java/it/gov/pagopa/debtposition/validation/DebtPositionValidation.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

[PPD-56] merged

---

gpd/api-test/DEBT_POSITION.postman_collection.json
gpd/src/main/java/it/gov/pagopa/debtposition/model/enumeration/DebtPositionStatus.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java

- Added management for REPORTED status
- Assigned test
Junit and postman test

[PPD-76] fully reported

---

gpd/api-test/DEBT_POSITION.postman_collection.json
gpd/openapi/openapi.json
gpd/src/main/java/it/gov/pagopa/debtposition/controller/BaseController.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/AppInfo.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/BaseControllerTest.java

- added health check service
- update openapi file
- assigned task
manual test postman and JUNIT

Ppd77 health check

---

gpd/api-test/DEBT_POSITION.postman_collection.json
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/OrganizationModelQueryBean.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/response/OrganizationListModelResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/response/OrganizationModelResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/repository/PaymentPositionRepository.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java

- Added service to return EC list (temporary solution)
- Assigned Task
postman test and junit test

[PPD-70] ec list

---

gpd/api-test/DEBT_POSITION.postman_collection.json
gpd/openapi/openapi.json
gpd/src/main/java/it/gov/pagopa/debtposition/DebtPositionApplication.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/configuration/api/IConfigurationsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/configuration/api/impl/ConfigurationsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/mapper/ConvertPOEntityToPOWithDebtor.java
gpd/src/main/java/it/gov/pagopa/debtposition/exception/AppError.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionWithDebtorInfoModelResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentPositionModelBaseResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/configurations/ConfigurationsService.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/ConfigurationsControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java

- Added api to check organization existence
- Created a section for configurations API
- Enriched the response for the call getOrganizationPaymentOptionByIUV (...)
- Assigned Task for project needs
postman test and junit test

[PPD-84] api organizations

---

local.settings.json.example
mock/gpd.py
payments/src/main/java/it/gov/pagopa/payments/config/WebServicesConfiguration.java
payments/src/main/java/it/gov/pagopa/payments/endpoints/PartnerEndpoint.java

Fix Namespace

---

.github/workflows/main.yml
payments/pom.xml
payments/src/main/java/it/gov/pagopa/payments/PaymentsApplication.java
payments/src/main/java/it/gov/pagopa/payments/config/LoggingAspect.java
payments/src/main/java/it/gov/pagopa/payments/controller/BaseController.java
payments/src/main/java/it/gov/pagopa/payments/service/GpdClient.java
payments/src/main/resources/application.properties
payments/src/test/java/it/gov/pagopa/payments/api/ApiTest.java
payments/src/test/resources/application.properties
reporting-service/host.json

added retryable annotation to the GPD calls

[PPD-104] Retry

---

.devops/deploy-pipelines.yml
report/bumper.sh
reporting-analysis/doc/db/flowsTable.puml
reporting-analysis/doc/db/flowsXMLBlob.puml
reporting-batch/doc/db/flowsQueue.puml
reporting-batch/doc/db/flowsTable.puml
reporting-batch/doc/db/organizationsQueue.puml
reporting-batch/doc/db/organizationsTable.puml
reporting-service/doc/db/flowsQueue.puml
reporting-service/doc/db/flowsXMLBlob.puml
reporting-service/doc/db/optionsQueue.puml

Added puml files for each module

Puml files

---

.devops/deploy-pipelines.yml
mock/gpd.py
reporting-batch/src/main/java/it/gov/pagopa/reporting/models/Organization.java
reporting-batch/src/main/java/it/gov/pagopa/reporting/models/Organizations.java
reporting-batch/src/main/java/it/gov/pagopa/reporting/service/OrganizationsService.java
reporting-batch/src/test/java/it/gov/pagopa/reporting/OrganizationsServiceIntegrationTest.java
reporting-batch/src/test/java/it/gov/pagopa/reporting/OrganizationsServiceTest.java

- modified `GET /organizations` message retrieved from GPD

[PPD-115] Organizations in reporting-batch

---

reporting-analysis/openapi/openapi.json

- added openapi spec for reporting-analysis

[PPD-115] Reporting Analysis openapi

---

reporting-batch/src/main/java/it/gov/pagopa/reporting/service/GPDService.java

- solved bug in reporting-batch regarding since date format pattern

[PPD-115] Reporting-batch: fix since date format 

---

reporting-analysis/host.json
reporting-analysis/openapi/openapi.json

- removed api prefix to urls
- fixed swagger

[PPD-115] Reporting analysis: route prefix

---

payments/src/main/java/it/gov/pagopa/payments/service/PartnerService.java
payments/src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
payments/src/test/resources/gpd/getPaymentOption.json

- fix status paVerify, paGetPayments

[PPD-115] Payments: fix status

---

gpd/src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java

- corrected the JUNIT test
- The test that was in error launched after 8 PM
Manual Junit test

[PPD-99] fix junit test: corrected the test

---

.devops/deploy-pipelines.yml

depends on https://github.com/pagopa/pagopa-infra/pull/203
- modified deploy pipeline to enable staging for GPD and Payments

[PPD-99] Enable GPD and Payments staging

---

payments/src/main/java/it/gov/pagopa/payments/config/LoggingAspect.java
payments/src/main/java/it/gov/pagopa/payments/config/RequestFilter.java
payments/src/main/java/it/gov/pagopa/payments/controller/BaseController.java
payments/src/main/java/it/gov/pagopa/payments/model/AppInfo.java
payments/src/main/java/it/gov/pagopa/payments/service/GpdClient.java
payments/src/main/resources/application-local.properties
payments/src/main/resources/application.properties
payments/src/main/resources/logback-spring.xml
payments/src/test/resources/application.properties

- added info to response `GET /info `
- added log
- added requestID

Payments Logging

---

payments/src/main/java/it/gov/pagopa/payments/entity/ReceiptEntity.java
payments/src/main/java/it/gov/pagopa/payments/entity/Status.java
payments/src/main/java/it/gov/pagopa/payments/model/PaymentOptionModelResponse.java
payments/src/main/java/it/gov/pagopa/payments/service/PartnerService.java
payments/src/test/java/it/gov/pagopa/payments/api/ApiTest.java

- added status for the receipt
- assigned task (usefull field for future api's)
Manual postman test and JUNIT test

[add receipt status]: add status for receipt based on GPD call

---

gpd/src/main/java/it/gov/pagopa/debtposition/service/configurations/ConfigurationsService.java

- changed checkOrganization behavior 
- increase performance
Postman and JUNIT

[fix-check-organizations]: changed findAll query with count query

---

api-test/Debt Position.postman_collection.json
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/PaymentOptionModel.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/main/resources/db/migration/V002__IDX.sql
gpd/src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

- added fee field management
- fee field always valued at 0
Postman test and junit test

[fix-fee]: added fee field management

---

.devops/deploy-pipelines.yml

updated condition in build pipeline to always skip integration/load test in production

updated condition in build pipeline

---

reporting-service/.env.sample
reporting-service/local.settings.json.example
reporting-service/src/main/java/it/gov/pagopa/reporting/entities/FlowEntity.java
reporting-service/src/main/java/it/gov/pagopa/reporting/functions/RetrieveDetails.java
reporting-service/src/main/java/it/gov/pagopa/reporting/service/FlowsService.java
reporting-service/src/test/java/it/gov/pagopa/reporting/service/FlowServiceIntegrationTest.java

depends on #75 
- remove flow from FlowsTable if retry versus node fails

[PPD-114] Remove flow from FlowsTable

---

gpd/script/01_UPD_TRANSFER_TRIM_IBAN

- add script for iban with space remediation
- bug
- script executed on dev

[fix iban]

---

README.md
api-test/Debt Position - Local.postman_environment.json
api-test/Debt Position.postman_collection.json
api-test/azure.dev.postman_environment.json
api-test/azure.uat.postman_environment.json
gpd/openapi/openapi.json
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/PaymentOptionModel.java
gpd/src/main/resources/application-local.properties
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
payments/src/main/java/it/gov/pagopa/payments/service/PartnerService.java
payments/src/main/resources/application-local.properties
payments/src/test/java/it/gov/pagopa/payments/endpoint/PartnerEndpointTest.java

- removed notblank annotation for paymentDateTime, paymentMethod and fee on GPD
- check on paymentDateTime on Payments

[PPD-157] Payment Option error

---

.devops/deploy-pipelines.yml
README.md
api-test/Debt Position - Local.postman_environment.json
api-test/Debt Position.postman_collection.json
api-test/azure.dev.postman_environment.json
api-test/azure.uat.postman_environment.json
gpd/openapi/openapi.json
gpd/pom.xml
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/PaymentOptionModel.java
gpd/src/main/resources/application-local.properties
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
payments/pom.xml
payments/src/main/java/it/gov/pagopa/payments/service/PartnerService.java
payments/src/main/resources/application-local.properties
payments/src/test/java/it/gov/pagopa/payments/endpoint/PartnerEndpointTest.java
report/pom.xml
reporting-analysis/load-test/README.md
reporting-analysis/load-test/src/modules/helpers.js
reporting-analysis/load-test/src/reporting-analysis_get_flow.js
reporting-analysis/load-test/src/reporting-analysis_get_flow_list.js
reporting-analysis/local.settings.json.example

- k6 test for report analysis getFlow and getFlowList call 
- test performance under load
- run in local environment

[PPD-151] load test reporting analysis

---

api-test/Debt Position.postman_collection.json
payments/pom.xml
payments/src/main/java/it/gov/pagopa/payments/controller/receipt/IPaymentsController.java
payments/src/main/java/it/gov/pagopa/payments/controller/receipt/impl/PaymentsController.java
payments/src/main/java/it/gov/pagopa/payments/entity/ReceiptEntity.java
payments/src/main/java/it/gov/pagopa/payments/model/PageInfo.java
payments/src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
payments/src/test/java/it/gov/pagopa/payments/api/PaymentsControllerTest.java
payments/src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
report/pom.xml

- added service filter to getOrganizationReceipts
- handled 404 error [PPD-180]
- separate the receipts to be sent to the PDA for the "canone unico"
- do not raise blocking error in case of 404 in the call to GPD
JUnit and Integration test
[PPD-180]: https://pagopa.atlassian.net/browse/PPD-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPD-165] separazione ricevute

---

.devops/deploy-pipelines.yml
.github/auto_assign.yml
.github/workflows/assignee.yml
.github/workflows/check_metadata_pr.yml
.github/workflows/deploy.yml
.github/workflows/sonar_analysis.yml
.github/workflows/update_infra.yml

Added a Github action.
on merge event the action gets the labels of the PR and call the Azure pipeline to bump the version and deploy in DEV.
- `breaking-change` -> major
- `enhancement` -> minor
- `bug` -> patch
- `skip-release` -> no bump version
Use one of the tag between `gpd`, `payments`, `reporting-service`, `reporting-batch` and `reporting-analysis` to specify the component to deploy
Note: To use the github action it needed an [access token ](https://docs.microsoft.com/it-it/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows).  ⚠️ **This token is personal and it expires.**
to automate the deploying phase
manually

[PPD-185] strategia rilasci versioning 

---

.github/workflows/check_metadata_pr.yml

fix GH Action

---

gpd/openapi/generate_openapi.sh
payments/openapi/generate_openapi.sh
payments/openapi/openapi.json

updated `openapi.json` file of payments

[Payments] Updated OpenApi

---

api-test/Debt Position.postman_collection.json
mock/gpd.py
mock/gps.py
payments/src/main/java/it/gov/pagopa/payments/endpoints/PartnerEndpoint.java
payments/src/main/java/it/gov/pagopa/payments/endpoints/validation/SoapMessageDispatcher.java
payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/DebtorModel.java
payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/PaymentPositionModel.java
payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/ServiceModel.java
payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/ServicePropertyModel.java
payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/SpontaneousPaymentModel.java
payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/SpontaneousPaymentOptionModel.java
payments/src/main/java/it/gov/pagopa/payments/model/spontaneous/TransferModel.java
payments/src/main/java/it/gov/pagopa/payments/service/GpsClient.java
payments/src/main/java/it/gov/pagopa/payments/service/PartnerService.java
payments/src/main/java/it/gov/pagopa/payments/utils/CommonUtil.java
payments/src/main/resources/application-local.properties
payments/src/main/resources/application.properties
payments/src/main/resources/xsd/common-types_2_0_0.xsd
payments/src/main/resources/xsd/general-service.xsd
payments/src/main/resources/xsd/paForNode.xsd
payments/src/test/java/it/gov/pagopa/payments/endpoint/PartnerEndpointTest.java
payments/src/test/java/it/gov/pagopa/payments/mock/PaDemandNoticePaymentReqMock.java
payments/src/test/java/it/gov/pagopa/payments/mock/PaDemandNoticePaymentResMock.java
payments/src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
payments/src/test/resources/application.properties
payments/src/test/resources/gps/createSpontaneousPayments.json

depends on https://github.com/pagopa/pagopa-infra/pull/305
added PaDemandPaymentNotice

[PPD-196] PaDemandPaymentNotice

---

payments/src/main/java/it/gov/pagopa/payments/config/AuthFeignConfig.java
payments/src/main/java/it/gov/pagopa/payments/endpoints/validation/PaymentValidator.java
payments/src/main/java/it/gov/pagopa/payments/service/ApiConfigClient.java
payments/src/main/resources/application-local.properties
payments/src/main/resources/application.properties
payments/src/test/java/it/gov/pagopa/payments/endpoints/validation/PaymentValidatorTest.java
payments/src/test/resources/application.properties

subscription key

---

payments/pom.xml
payments/src/main/java/it/gov/pagopa/payments/service/PartnerService.java
payments/src/main/java/it/gov/pagopa/payments/utils/CommonUtil.java
payments/src/main/resources/application-local.properties
payments/src/main/resources/application.properties
payments/src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
report/pom.xml

fix: Properties

---

.gitignore
payments/integration-test/README.md
payments/integration-test/config/properties.json
payments/integration-test/features/payments.feature
payments/integration-test/package.json
payments/integration-test/step_definitions/support/common.js
payments/integration-test/step_definitions/support/gps_client.js
payments/integration-test/step_definitions/support/payments_client.js
payments/integration-test/step_definitions/support/steps.js
payments/load-test/README.md
payments/load-test/src/dev.environment.json
payments/load-test/src/grafana.sh
payments/load-test/src/payments_demand_notice.js
payments/load-test/src/payments_workflow.js
payments/load-test/src/test-types/load.json
payments/load-test/src/test-types/spike.json
payments/load-test/src/test-types/stress.json

depends on #112 
See here https://pagopa.atlassian.net/wiki/spaces/PPD/pages/541983221/Report+k6

[Payments] Load Test with K6

---

reporting-analysis/src/main/java/it/gov/pagopa/reporting/GetFlowList.java

fix: Change authLevel GetFlowList

---

gpd/src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
payments/pom.xml
report/pom.xml
reporting-analysis/pom.xml
reporting-analysis/src/main/java/it/gov/pagopa/reporting/GetFlowList.java

- fix update debt position
- a violated constraint error occurred during the update operation
- manual and junit test

[PAGOPA-703] update error: fix unique constraint error

---

.devops/deploy-pipelines.yml
gpd/doc/db/re.puml
gpd/pom.xml
gpd/src/main/java/it/gov/pagopa/debtposition/entity/PaymentPosition.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/main/resources/db/migration/V005__ALTER_PAYMENTDATE.sql
report/pom.xml

Previously, if a payment option (either partial and not) was paid by debtor, the parent payment position contains the main information related to the payment status and the user that reads this object is not aware of the date when the payment position has been collected or partially collected.
With this feature, a new field is added in order to relate the information about the last paid payment option to the parent payment position. So, this new information enrich the payment position in order to execute more search and analysis by the APIs user.
- Added new field, named `payment_date`, on `payment_position` table
- Added handling logic on 'pay' operation for this date.
This feature is needed in order to permits, among other things, to filtering payment option by payment date and show …

[PAGOPA-751] Payment date on Debt Position

---

gpd/pom.xml
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/pd/actions/PaymentPositionActionsService.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
gpd/src/main/java/it/gov/pagopa/debtposition/util/PublishPaymentUtil.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionActionsControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
report/pom.xml

This pr adds the creation + publication functionality. Through a query parameter added to the URL it is possible to decide if the debt position created is to be immediately published or not. 
This enhancement is needed to speed up the publication process and avoid some slow steps. 
This has been tested manually and through unit testing.

feat gpd: adding creation + publication PAGOPA-639

---

gpd/openapi/openapi.json

chore: update openapi

---

gpd/.gitignore
gpd/integration-test/src/features/debt-position-manage.feature
gpd/integration-test/src/step_definitions/support/clients/gpd_client.js
gpd/integration-test/src/step_definitions/support/logic/gpd_logic.js
gpd/integration-test/src/step_definitions/support/steps.js
gpd/integration-test/src/step_definitions/support/utility/helpers.js

- 3 scenarios regarding filters on the GET `/organizations/{organizationfiscalcode}/debtpositions` added
- `executeDebtPositionDeletion` fixed

test: Add integration test PAGOPA-736 

---

.github/workflows/create_dashboard.yaml
.identity/.terraform.lock.hcl
.identity/00_locals.tf
.identity/00_main.tf
.identity/00_variables.tf
.identity/01_data.tf
.identity/02_application_action.tf
.identity/02_application_action_auth.tf
.identity/03_github_environment.tf
.identity/99_outputs.tf
.identity/env/dev/backend.ini
.identity/env/dev/backend.tfvars
.identity/env/dev/terraform.tfvars
.identity/env/prod/backend.ini
.identity/env/prod/backend.tfvars
.identity/env/prod/terraform.tfvars
.identity/env/uat/backend.ini
.identity/env/uat/backend.tfvars
.identity/env/uat/terraform.tfvars
.identity/terraform.sh
.opex/env/prod/backend.ini
.opex/env/prod/backend.tfvars
.opex/env/prod/config.yaml
.opex/env/prod/terraform.tfvars

- added `.identity` folder
- added `.opex` folder
- added github action `create_dashboard.yaml`

[PAGOPA-777] Opex Dashboard

---

gpd/flyway.conf
gpd/pom.xml
gpd/src/main/java/it/gov/pagopa/debtposition/DebtPositionApplication.java
gpd/src/main/java/it/gov/pagopa/debtposition/entity/Transfer.java
gpd/src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPOEntityToPOWithDebtor.java
gpd/src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/response/TransferModelResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionModel.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/pd/Stamp.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/pd/TransferModel.java
gpd/src/main/java/it/gov/pagopa/debtposition/model/pd/response/TransferModelResponse.java
gpd/src/main/java/it/gov/pagopa/debtposition/scheduler/Scheduler.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
gpd/src/main/java/it/gov/pagopa/debtposition/util/CommonUtil.java
gpd/src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
gpd/src/main/resources/application-h2.properties
gpd/src/main/resources/application-local.properties
gpd/src/main/resources/db/migration/V006__ALTER_TRANSFER.sql
gpd/src/test/java/it/gov/pagopa/debtposition/TestUtil.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
gpd/src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
gpd/src/test/java/it/gov/pagopa/debtposition/scheduler/SchedulerTest.java
payments/load-test/src/result.html

Add Stamp in input and responses

[PAGOPA-812] Stamp

---

.github/workflows/integration_test.yml
integration-test/run_integration_test.sh

Fix pipeline integration

---

gpd/openapi/openapi.json
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
gpd/src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
gpd/src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java

- added publishing flag on update debt position
- aca business request
manual and junit test

[PAGOPA-858] added publishing flag on update

---

gpd/integration-test/src/config/.env.dev
gpd/integration-test/src/config/.env.local
gpd/integration-test/src/config/.env.uat
gpd/integration-test/src/features/debt-position-manage.feature
gpd/integration-test/src/features/debt-position-pay.feature
gpd/integration-test/src/features/debt-position-update-and-publish.feature
gpd/integration-test/src/step_definitions/support/clients/gpd_client.js
gpd/integration-test/src/step_definitions/support/logic/common_logic.js
gpd/integration-test/src/step_definitions/support/logic/gpd_logic.js
gpd/integration-test/src/step_definitions/support/steps.js
gpd/integration-test/src/step_definitions/support/utility/request_builders.js

This PR contains several changes made on integration tests in order to add a test case for `toPublish` flag in update operation.
- Added new test case for integration test
This changes are required in order to include a test for update-with-publish operation 
- Tested in local environment
- Tested in DEV environment

[PAGOPA-904] Update on Integration test for toPublish functionality 

---

.gitignore
gpd/pom.xml
gpd/src/main/resources/application-h2.properties
gpd/src/main/resources/application-local.properties
gpd/src/main/resources/application.properties
gpd/src/test/resources/application.properties
helm/.helmignore
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
report/pom.xml

- Add and config actuator library for liveness and readiness probe
- Add helm values

feat: Add helm values and health endpoints [PAGOPA-1038]

---

.github/release.yml
.github/workflows/anchore.yml
.github/workflows/check_pr.yml
.github/workflows/deploy_with_github_runner.yml
.github/workflows/integration_test.yml
.github/workflows/release_deploy.yml
.github/workflows/update_code.yml

Some GHAs were added/modified with the aim of migrating the CI/CD.
GHA added:
- `.github/release.yml`
- `.github/workflows/anchore.yml`
- `.github/workflows/check_pr.yml`
- `.github/workflows/deploy_with_github_runner.yml`
- `.github/workflows/release_deploy.yml`
- `.github/workflows/update_code.yml`
GHA updated:
- `.github/workflows/integration_test.yml`

feat: Add and update GHA [PAGOPA-1039]

---

gpd/pom.xml
gpd/src/main/resources/application-h2.properties
gpd/src/main/resources/application-local.properties
gpd/src/main/resources/application.properties
gpd/src/test/resources/application.properties
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
report/pom.xml

- the API for retrieving metrics from the `gpd-core` micro-service is added
- helm values were modified using [metrics-api](https://keda.sh/docs/2.10/scalers/metrics-api/) to do horizontal autoscaling of the micro-service. Specifically, the application scales when the p(99) calculated on all http requests is greater than 50 ms.

AKS autoscaling via KEDA [PAGOPA-1040]

---

.github/workflows/create_dashboard.yaml
.github/workflows/db_migration_with_github_runner.yml
.github/workflows/integration_test.yml
.github/workflows/release_deploy.yml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_internal.json
pom.xml

- Fix path in `create_dashboard` and `integration_test` pipeline
- Fix `db_migration` pipeline

fix: Update Actions

---

.github/workflows/db_migration_with_github_runner.yml
.github/workflows/deploy_with_github_runner.yml
load-test/src/test-types/constant.json
load-test/src/test-types/smoke.json

Update GH Runner

---

helm/values-prod.yaml

fix: Url metrcs autoscaling prod

---

helm/values-prod.yaml

fix: Disable metrics-api scale prod

---

helm/values-prod.yaml
helm/values-uat.yaml

- Update `SQL_LOG_LEVEL` and `SQL_BINDER_LOG_LEVEL` to `INFO` level.
Adjusting log verbosity.
Local testing.

ci: Update log level [PAGOPA-1150] 

---

openapi/openapi_external.json
openapi/openapi_internal.json
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/repository/PaymentPositionRepository.java

- Update page max size constraints for `GET /organizations/{organizationfiscalcode}/debtpositions` API
- this change is necessary in order to avoid high response times

fix: Update param validation [PAGOPA-1145] 

---

.github/workflows/integration_test.yml

- Set `dev` as default environment
- For scheduled tests (default `dev`), GHA was taking secrets from the wrong environment (UAT)

fix: Update integration test GHA

---

openapi/openapi_external.json
openapi/openapi_internal.json
openapi/openapi_send.json
src/main/resources/application.properties
src/test/java/it/gov/pagopa/debtposition/OpenApiGenerationTest.java
src/test/resources/application.properties

In this PR `OpenApiGenerationTest` was updated in order to save an OpenAPI containing the REST resources and verbs that match these paths:
- `/organizations/{organizationfiscalcode}/paymentoptions/{iuv}/notificationfee`
- `/organizations/{organizationfiscalcode}/paymentoptions/{iuv}`
- `/info`

feat: Add SEND OpenAPI [PAGOPA-1267]

---

.github/workflows/integration_test.yml

- The default environment of the integration test job to `'uat'` has been updated to set the right variables and secrets;
- The default environment to `'uat'` when running `run_integration_test.sh` has been updated.
During the weekend AKS nodes are turned off in the development environment, we can run tests in the `UAT` environment.

ci: Update integration test default env

---

.github/workflows/code_review.yml
Dockerfile
docker/run_docker.sh
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
integration-test/src/config/.env.dev
integration-test/src/config/.env.local
integration-test/src/config/.env.uat
integration-test/src/features/debt-position-manage.feature
integration-test/src/step_definitions/support/logic/common_logic.js
integration-test/src/step_definitions/support/logic/gpd_logic.js
integration-test/src/step_definitions/support/steps.js
integration-test/src/step_definitions/support/utility/data.js
integration-test/src/step_definitions/support/utility/request_builders.js
openapi/openapi_external.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java

- added integration test scenario for the update fee 
- test the correct functioning of the logic
- manual test in local env

feat: [PAGOPA-1295] integration test for update fee scenario

---

integration-test/src/.gitignore
integration-test/src/features/debt-position-create-and-publish.feature
integration-test/src/features/debt-position-manage.feature
integration-test/src/step_definitions/support/clients/gpd_client.js
integration-test/src/step_definitions/support/logic/common_logic.js
integration-test/src/step_definitions/support/logic/gpd_logic.js
integration-test/src/step_definitions/support/steps.js
integration-test/src/step_definitions/support/utility/request_builders.js

- added "enti plurintermediati" scenarios in the integration tests
- check the correct functioning of the segregation codes filter
- local run of the integration tests
- [tested](https://github.com/pagopa/pagopa-debt-position/actions/runs/6629426605) in DEV environment

feat: [PagoPa-1296] Integration Test Enti Plurintermediati

---

src/main/java/it/gov/pagopa/debtposition/exception/ErrorHandler.java

- Add ExceptionHandler for javax.validation.ConstraintViolationException
- This type of exception depends on the client request. Currently when it occurs the backend returns 500, it should return 400 instead.
- via POSTMAN in local environment;

fix: Add ExceptionHandler for ConstraintViolationException [PAGOPA-1319]

---

openapi/openapi_external.json
openapi/openapi_internal.json
openapi/openapi_send.json
src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java

Add `configureGroupOpenApi` and apply the `OpenApiCustomiser` `addCommonHeaders()` to all OpenAPI.
bug: `Request-ID` as request header was added only in the first grouped OpenAPI, `openapi_external.json`

fix: Update SwaggerConfig for grouped OpenAPI [PAGOPA-1304]

---

.github/workflows/code_review.yml
.identity/03_github_environment.tf
integration-test/src/config/.env.dev
integration-test/src/config/.env.local
integration-test/src/config/.env.uat
integration-test/src/features/debt-position-manage.feature
integration-test/src/features/debt-position-pay.feature
integration-test/src/step_definitions/support/clients/gpd_client.js
integration-test/src/step_definitions/support/logic/common_logic.js
integration-test/src/step_definitions/support/steps.js

Timeout for the list of debt positions with segregation code is extended. Also, assertSize is replaced with assertMinSize since the exact number of Debt Position is not known a priori since the segregation code in input is random.
Failing integration test in UAT environment.

chore: Fix integration test [PAGOPA-1330] 

---

openapi/openapi_external.json
openapi/openapi_internal.json
openapi/openapi_send.json
src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
src/main/java/it/gov/pagopa/debtposition/entity/PaymentOptionMetadata.java
src/main/java/it/gov/pagopa/debtposition/entity/Transfer.java
src/main/java/it/gov/pagopa/debtposition/entity/TransferMetadata.java
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPOEntityToPOWithDebtor.java
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionModelResponse.java
src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionWithDebtorInfoModelResponse.java
src/main/java/it/gov/pagopa/debtposition/model/payments/response/TransferModelResponse.java
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionMetadataModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/TransferMetadataModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/TransferModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentOptionMetadataModelResponse.java
src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentOptionModelResponse.java
src/main/java/it/gov/pagopa/debtposition/model/pd/response/TransferMetadataModelResponse.java
src/main/java/it/gov/pagopa/debtposition/model/pd/response/TransferModelResponse.java
src/main/resources/db/migration/V009__ADD_METADATA_TABLES.sql
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
src/test/java/it/gov/pagopa/debtposition/dto/PaymentOptionDTO.java
src/test/java/it/gov/pagopa/debtposition/dto/PaymentOptionMetadataDTO.java
src/test/java/it/gov/pagopa/debtposition/dto/TransferDTO.java
src/test/java/it/gov/pagopa/debtposition/dto/TransferMetadataDTO.java
src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

- added metadata on gpd PO and Transfer
- business request

[PagoPa-1333] gpd metadata

---

README.md
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

- Add metadata {`PO_TYPE`, `ACA`} if `IUPD` of posted Payment Position starts with `ACA`.
- Also, the `README.md` file that referenced the old test pipeline has been updated.

feat: Add new metadata when create payment position [PAGOPA-1348]

---

src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

This issue cannot be handled with a metadata because it could be changed during the history of a debt position and payment.

[PAGOPA-1348] chore: rollback PO_TYPE metadata

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
integration-test/src/step_definitions/support/logic/common_logic.js
integration-test/src/step_definitions/support/steps.js
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/validator/ValidDebtPositionsSize.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/validator/ValidMaxDebtPositions.java
src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
src/main/java/it/gov/pagopa/debtposition/model/pd/MultiplePaymentPositionModel.java
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
src/main/resources/application.properties
src/test/java/it/gov/pagopa/debtposition/OpenApiGenerationTest.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/dto/MultiplePaymentPositionDTO.java
src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
src/test/resources/application.properties

Depends on [INFRA](https://github.com/pagopa/pagopa-infra/pull/1550)
- added new API: `POST /organizations/{organizationfiscalcode}/debtpositions/bulk `
- added to gpd the possibility of mass loading of debit positions
- junit and manual test

feat: [PagoPA-1361] Bulk Loading

---

.gitignore
helm/values-prod.yaml
helm/values-uat.yaml

Update with `preferredDuringSchedulingIgnoredDuringExecution`:
_The scheduler tries to find a node that meets the rule. If a matching node is not available, the scheduler still schedules the Pod._
- weight is `100`, this specifies the weight of this anti-affinity rule.
- topology key is `topology.kubernetes.io/zone`, the node must have a label with the key `topology.kubernetes.io/zone`
This pod anti-affinity rule ensures that pods with the `app.kubernetes.io/instance: gpd-core` label are spread across different availability zones in the gps namespace.

[BCDR] feat: Update Pod affinity

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java

Bug fix for the bulk insertion of debt positions
This change was required for the correct functionality when adding a payment option with metadata equal to NULL. This fix is necessary to avoid a nullpointerexception in that instance.
when `transferMetadata` is null -> `201` Created with `transferMetadata = []`
when `paymentOptionMetadata` is null -> `201` Created with `paymentOptionMetadata = []`
This change has been tested manually and through junit tests.
DEV environment ✅

PAGOPA-1392 fixing bulk null pointer metadata

---

.gitignore
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
src/test/java/it/gov/pagopa/debtposition/dto/PaymentPositionDTO.java

- made the field switch_to_expired mandatory
- "switch_to_expired" violates not-null constraint error
- manual test
- tested in DEV ✅

bug: [PAGOPA-1393] switch to expired error

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
integration-test/src/config/.env.dev
load-test/src/create_debt_position.js
load-test/src/get_debt_position_list.js
load-test/src/modules/data.js
load-test/src/payments_workflow.js
load-test/src/publish_workflow.js
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/pageable/PageCustom.java
src/main/java/it/gov/pagopa/debtposition/repository/PaymentOptionRepository.java
src/main/java/it/gov/pagopa/debtposition/repository/PaymentPositionRepository.java
src/main/java/it/gov/pagopa/debtposition/repository/specification/PaymentOptionByAttribute.java
src/main/java/it/gov/pagopa/debtposition/repository/specification/PaymentPositionByOptionsAttribute.java
src/main/java/it/gov/pagopa/debtposition/repository/specification/PaymentPositionByOrganizationFiscalCode.java
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/main/java/it/gov/pagopa/debtposition/util/CommonUtil.java
src/main/resources/db/migration/V010__ADD_PP_INDEXES.sql
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java

- removed EntityGraph to allow offset and limit
- out of memory error for in memory pagination
Local test

bug: [PAGOPA-1377] out of memory error

---

src/main/java/it/gov/pagopa/debtposition/model/pd/TransferModel.java
src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

- exclusivity rules changed
- it was impossible to create a debt position with iban and postal iban
- manual and junit test

bug: [PAGOPA-1498] iban postalIban pair

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml

Changing pg conn string in order to redirect to new dns
This change is needed for the multizone implementation

PAGOPA-1436 new pg dns uat

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/resources/application-h2.properties
src/main/resources/db/migration/V012__ALTER_NAV.sql

- added flyway script to manage the new NAV field
- have the NAV code as database information

feat: [PAGOPA-1546] NAV field

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/pd/actions/api/impl/DebtPositionActionsController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionModel.java
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/main/resources/application-h2.properties
src/main/resources/db/migration/V012__ALTER_NAV.sql
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionActionsControllerTest.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/dto/PaymentOptionDTO.java

- added nav managment
- identify a payment via NAV instead of IUV

feat: [PagoPa-1548] public api

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

- Update [pg connection params](https://jdbc.postgresql.org/documentation/use/#connection-parameters) with `tcpKeepAlive` that enables TCP keep-alive probe

chore: Update pg connection params

---

helm/values-prod.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/entity/PaymentPosition.java
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
src/main/java/it/gov/pagopa/debtposition/repository/specification/PaymentPositionByIUPDList.java
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

- Add bulk UPDATE API
- Massive Debt Position Update
- Unit test

[PAGOPA-1588] feat: add bulk update

---

pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/exception/AppError.java
src/main/java/it/gov/pagopa/debtposition/model/pd/MultipleIUPDModel.java
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/dto/MultipleIUPDDTO.java

- Add bulk DELETE API
- Massive Debt Position DELETE for external and internal API
- JUnit test
- Testing in local + DEV environment

feat: add bulk DELETE [PAGOPA-1589] 

---

src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java

- add pattern matching in `DebtPositionController`
- fix log injection

fix: update pattern matcher

---

openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java

- Update max length for the following field: payment-position.officeName, payment-position.companyName, payment-option.description
- SANP compliance

chore: update payment position and option constraints [PAGOPA-1680] 

---

openapi/openapi_external.json

- Fix url base path
- Add v1 and v2 to API path

chore: Update openapi_external.json

---

src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java

- Reducing the default limit
- Improve performance when default is used (temporary mitigation)

chore: Adjust `getOrganizationDebtPositions` default limit [PAGOPA-1757]

---

.github/workflows/report.yml
gpd-report/.env.sample
gpd-report/README.md
gpd-report/go.mod
gpd-report/go.sum
gpd-report/main.go
gpd-report/repository/repository.go

feat: Add slack report action

---

.github/workflows/report.yml
gpd-report/.env.sample
gpd-report/main.go
gpd-report/repository/repository.go

- Refactoring GitHub Action (move Go build in report job)
- Add metrics on last year
- slack report

chore: Refactoring slack report

---

.github/workflows/deploy_with_github_runner.yml
.github/workflows/report.yml

- Update Runner self-hosted-runner version
- Fix issue: execution stuck

fix: Update Runner self-hosted-runner version

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/actions/api/impl/DebtPositionActionsController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPOEntityToPOWithDebtor.java
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertTransferToTransferResponse.java
src/main/java/it/gov/pagopa/debtposition/model/pd/Stamp.java
src/main/java/it/gov/pagopa/debtposition/util/ObjectMapperUtils.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerBulkTest.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/dto/TransferDTO.java
src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java

- Update and check all responses
- `Stamp` object mapping fix

[PAGOPA-1800] fix: Update Stamp mapping

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertTransferToTransferResponse.java
src/main/java/it/gov/pagopa/debtposition/util/ObjectMapperUtils.java

- Update `Transfer` to `TransferModel` converter
- Update `Transfer` to `TransferModelResponse` converter
- when all the `Stamp` attributes are `null` it is necessary to return `null` in the responses which contains the `Stamp` object

[PAGOPA-1825] fix: Update Stamp mapping in responses

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java

- Update `page` default-value and set required to `false`
- Page could be not required

Fix default page

---

.github/workflows/report.yml

chore(report.yml): Update DAYS

---

openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java

- Update `IUV` regex validation in `GetDebtPositionByIUV`
- `IUV` can be composed by letter

fix: Update regex constraints [PAGOPA-1924] 

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/DebtPositionApplication.java
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java

- Add mapping for `pull` parameter

[PAGOPA-1970] fix: Adjust PaymentPosition model converter

---

.github/workflows/report.yml

When the action is executed in a scheduled way the environment variable is `null`, so it should be adjusted and by default it should be `prod`
Fix scheduled report generation GitHub Action, currently when it is executed programmatically it fails to login because following environment related params are not valued 
```
client_id
tenant_id
subscription_id
container_app_environment_name
resource_group_name
```

fix: Update report action

---

src/main/java/it/gov/pagopa/debtposition/model/pd/TransferModel.java

- Add `@Valid` annotation to `Stamp` contained in the `Transfer`
- Prevent `Stamp` with size greater than 72 chars.
- Prevent `value too long for type character varying(255)`

[PAGOPA-2098] fix(Stamp): Add validation check

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentPositionModelBaseResponse.java
src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPaidPaymentsControllerTest.java
src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPartiallyPaidPaymentsControllerTest.java
src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPartiallyReportedPaymentsControllerTest.java
src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentReportedPaymentsControllerTest.java

- remove flag pull from request/response models. It's still exist as column with default value = true.
[link swagger](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pagopa/pagopa-debt-position/refs/heads/PAGOPA-2325-gpd-core/openapi/openapi_internal.json)
🤖 junit
✋ manual

chore(flag-pull): Remove Pull Flag

---

helm/values-dev.yaml

chore: Fix Dev deploy 2 pglfex

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_send.json
pom.xml
src/main/resources/db/migration/V018__UPDATE_UNIQUE_TRANSFER_CONSTRAINT.sql

- Update `db/migration` with `V018__UPDATE_UNIQUE_TRANSFER_CONSTRAINT.sql` with new constraint `unique_transfer`
the constraint is intended to prevent a PT/EC from providing `Transfers` with duplicate `idTransfer` within the same `payment_option`.
The uniqueness constraint is relaxed and shifted from the triple `(iuv, organization_fiscal_code, transfer_id)` to `(iuv, organization_fiscal_code, transfer_id, payment_option_id)`
Why? Because it must be possible to create 2 transfers with the same `(iuv, organization_fiscal_code, transfer_id)` on condition that they belong to different `payment_option`.
- DEV environment

[PAGOPA-2354] feat: Update `unique_transfer` constraint

---

openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_internal_massive.json
openapi/openapi_send.json
src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java

chore: Update SwaggerConfig.java

---

src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
src/main/resources/application.properties

fix: Update payStandIn default

---

src/main/java/it/gov/pagopa/debtposition/model/pd/MultipleIUPDModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/MultiplePaymentPositionModel.java

- Set max payload size for bulk APIs

fix: Update bulk APIs payload max size

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_internal_massive.json
openapi/openapi_send.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
src/main/java/it/gov/pagopa/debtposition/model/enumeration/DebtPositionStatus.java
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
src/main/java/it/gov/pagopa/debtposition/util/CommonUtil.java
src/main/java/it/gov/pagopa/debtposition/util/Constants.java
src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
src/main/java/it/gov/pagopa/debtposition/util/PublishPaymentUtil.java
src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
src/test/java/it/gov/pagopa/debtposition/scheduler/ExpiredPositionsSchedulerTest.java

- changes to allow updating a debt position in expired status
- allows you to bring back a debt position in expired status
- Local manual and junit test
- [DEV integration test](https://github.com/pagopa/pagopa-debt-position/actions/runs/12348851734)

feat: [PagoPA-2459] - expired status

---

.github/workflows/deploy_with_github_runner.yml
.github/workflows/release_deploy.yml
.github/workflows/unistall_deploy.yml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_external.json
openapi/openapi_external_massive.json
openapi/openapi_internal.json
openapi/openapi_internal_massive.json
openapi/openapi_send.json
pom.xml
src/main/resources/application.properties

🆙 Bump to Helm Chart `v5.11.0`
🚰 new Github Actions to handle canary v5
[Jira Issue](https://pagopa.atlassian.net/browse/PAGOPA-2502)
✋ manually
[![Release And Deploy](https://github.com/pagopa/pagopa-debt-position/actions/workflows/release_deploy.yml/badge.svg?branch=PAGOPA-2502-gpd-upgrade-and-release-canary-version-with-hikari)](https://github.com/pagopa/pagopa-debt-position/actions/workflows/release_deploy.yml)

chore(helm): upgrade microservice-chart to version 5.11.0 and create a Hikari beta version

---

.identity/00_data.tf
.identity/03_github_environment.tf
.identity/terraform.sh

chore: Update identity

---

openapi/openapi_aca_v1.json
openapi/openapi_external_v1.json
openapi/openapi_external_v2.json
openapi/openapi_external_v3.json
openapi/openapi_internal_v1.json
openapi/openapi_internal_v2.json
openapi/openapi_send_v1.json
src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java

fix: Openapi send

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_aca_v1.json
openapi/openapi_external_v1.json
openapi/openapi_external_v2.json
openapi/openapi_external_v3.json
openapi/openapi_internal_v1.json
openapi/openapi_internal_v2.json
openapi/openapi_send_v1.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java

[PIDM-477] fix: Handle old notification fee

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_aca_v1.json
openapi/openapi_external_v1.json
openapi/openapi_external_v2.json
openapi/openapi_external_v3.json
openapi/openapi_internal_v1.json
openapi/openapi_internal_v2.json
openapi/openapi_send_v1.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java

You cannot inject an entity at runtime because Hibernate try to execute statement and we get this error `"could not execute statement; SQL [n/a]; constraint [payment_option_id\" of relation \"payment_option_metadata]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"`

[PIDM-433] fix: Move metadata injection to controller

---

integration-test/src/features/debt-position-manage.feature

[PIDM-433] chore: Disable flaky test

---

helm/values-prod.yaml

chore: Update canary version

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_aca_v1.json
openapi/openapi_external_v1.json
openapi/openapi_external_v2.json
openapi/openapi_external_v3.json
openapi/openapi_internal_v1.json
openapi/openapi_internal_v2.json
openapi/openapi_send_v1.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
src/main/java/it/gov/pagopa/debtposition/model/payments/PaymentOptionModel.java
src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
src/main/resources/db/migration/V027__ALTER_PO_PSP_FIELDS.sql

[PAGOPA-3031] feat: add PSP fields

---

openapi/openapi_aca_v1.json
openapi/openapi_external_v1.json
openapi/openapi_external_v2.json
openapi/openapi_external_v3.json
openapi/openapi_internal_v1.json
openapi/openapi_internal_v2.json
openapi/openapi_send_v1.json
src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionModel.java
src/main/java/it/gov/pagopa/debtposition/model/pd/TransferModel.java
src/main/java/it/gov/pagopa/debtposition/model/v3/InstallmentModel.java

- Added validation annotation `@Min(value=1L)` to the `amount` property of `TransferModel`, `PaymentOptionModel`, `InstallmentModel` 
- Updated openapi
[PIDM-700](https://pagopa.atlassian.net/browse/PIDM-700)
[PIDM-700]: https://pagopa.atlassian.net/browse/PIDM-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [PIDM-700] TransferModel & PaymentOptionModel & InstallmentModel amount cannot be zero

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_aca_v1.json
openapi/openapi_external_v1.json
openapi/openapi_external_v2.json
openapi/openapi_external_v3.json
openapi/openapi_internal_v1.json
openapi/openapi_internal_v2.json
openapi/openapi_send_v1.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/DebtPositionApplication.java
src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPOEntityToPaidPOModel.java
src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaidPaymentOptionModel.java
src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java

[PAGOPA-3112] feat: Update pay API response

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi_aca_v1.json
openapi/openapi_external_v1.json
openapi/openapi_external_v2.json
openapi/openapi_external_v3.json
openapi/openapi_internal_v1.json
openapi/openapi_internal_v2.json
openapi/openapi_send_v1.json
pom.xml
src/main/java/it/gov/pagopa/debtposition/mapper/ConverterV3PPModelToEntity.java
src/test/java/it/gov/pagopa/debtposition/mapper/ConverterV3PPModelToEntityTest.java

hotfix: set description by installment

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

- added rolling update strategy (maxUnavailable, maxSurge)
- overridden deployment replicas to match HPA minReplica config
This change is required so the pod replicas are set to match the autoscaling config during deploy, to avoid starting the service with 1 pod when there is traffic on the service/
This also ensures zero-downtime deployments by keeping all existing pods running until new versions are healthy and ready, then replacing them one at a time.

feat: [PIDM-504] update deploy config and strategy
